project_id = "habbit-dashboard"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[storage.vector]
enabled = false

[auth]
enabled = true
site_url = "https://1421582341.github.io/habbit-dashboard/"
additional_redirect_urls = ["http://127.0.0.1:8080", "http://localhost:8080"]
enable_signup = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[functions.shortcut-ingest]
verify_jwt = false
